##############################
### WINDOWS AND WORKSPACES ###
##############################

## Use hyprctl clients to look for window class

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule = match:class kvantummanager, float True
windowrule = match:class qt5ct, float True
windowrule = match:class qt6ct, float True
windowrule = match:class nwg-look, float True
windowrule = match:class org.kde.ark, float True
windowrule = match:class pavucontrol, float True
windowrule = match:class blueman-manager, float True
windowrule = match:class nm-applet, float True
windowrule = match:class nm-connection-editor, float True
windowrule = match:class org.kde.polkit-kde-authentication-agent-1, float True
windowrule = match:class com.moonlight_stream.Moonlight, fullscreen True

windowrule = match:class .*, maximize silent  # You'll probably like this.
windowrule = match:class .*, opacity 0.93 0.70 
windowrule = match:float True, center on

windowrule = match:class kitty, workspace 1
windowrule = match:class brave-browser, workspace 2
windowrule = match:class Spotify, workspace 5
windowrule = match:class com.mastermindzh.tidal-hifi, workspace 5
windowrule = match:class REAPER, match:float False, workspace 3
windowrule = match:class REAPER, match:float True, workspace 3 silent
windowrule = match:class Godot, workspace 3
windowrule = match:class com.vscodium.codium, workspace 3
windowrule = match:class org.kde.kdenlive, workspace 3
windowrule = match:class Audacity, workspace 3
windowrule = match:class gimp, workspace 3
windowrule = match:class steam, workspace 4
windowrule = match:class CurseForge, workspace 4
windowrule = match:class heroic, workspace 4
windowrule = match:class discord, workspace 4
windowrule = match:class Element, workspace 4
windowrule = match:class brave-nngceckbapebfimnlniiiahkandclblb-Default, float True
windowrule = match:class jetbrains-idea, workspace 3
windowrule = match:class jetbrains-pycharm, workspace 3
windowrule = match:class jetbrains-rubymine, workspace 3
windowrule = match:class jetbrains-rustrover, workspace 3
