indicator-idle-visible
line-uses-inside
clock
# show-failed-attempts

image=~/Pictures/wallpapers/01.jpg
scaling=fill
indicator-radius=150
indicator-thickness=9
font=JetBrainsMono
font-size=100
effect-pixelate=30
effect-vignette=0.9:0.2
# grace=15

inside-color=#3080D077
inside-clear-color=#50A0F099
inside-caps-lock-color=#50A0F099
inside-ver-color=#70A0E0BB
inside-wrong-color=#B0908099

bs-hl-color=#888888
key-hl-color=#FFFFFF
separator-color=#50D090

text-color=#FFFFFF
text-clear-color=#FFFFFF
text-caps-lock-color=#FFFFFF
text-ver-color=#FFFFFF
text-wrong-color=#FFFFFF

ring-color=#50D090
ring-clear-color=#50A0F099
ring-caps-lock-color=#50A0F099
ring-ver-color=#70A0E0BB
ring-wrong-color=#B0908099
